# Generated by Django 5.0.14 on 2026-05-31 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ploegnaam')),
                ('drink_type', models.CharField(blank=True, default='Bier', max_length=100, verbose_name='Dranksoort')),
            ],
            options={
                'verbose_name': 'Ploeg',
                'verbose_name_plural': 'Ploegen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naam')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.team')),
            ],
            options={
                'verbose_name': 'Speler',
                'verbose_name_plural': 'Spelers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naam')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('setup', 'Opzet'), ('round_robin', 'Pouleronde'), ('knockout', 'Knock-out'), ('finished', 'Afgelopen')], default='setup', max_length=20)),
                ('format', models.CharField(choices=[('round_robin', 'Poule (iedereen speelt X keer)'), ('knockout', 'Knock-out (kwart/semi/finale)'), ('combined', 'Combinatie (poule → knock-out)')], default='round_robin', max_length=20, verbose_name='Formaat')),
                ('cup_count', models.PositiveIntegerField(default=10, verbose_name='Aantal bekers')),
                ('games_per_team', models.PositiveIntegerField(default=3, verbose_name='Wedstrijden per ploeg (poule)')),
                ('knockout_advancement', models.PositiveIntegerField(default=8, verbose_name='Ploegen naar knock-out')),
                ('points_win', models.PositiveIntegerField(default=3, verbose_name='Punten voor winst')),
                ('points_draw', models.PositiveIntegerField(default=1, verbose_name='Punten voor gelijk')),
                ('points_loss', models.PositiveIntegerField(default=0, verbose_name='Punten voor verlies')),
                ('points_bonus_all_cups', models.PositiveIntegerField(default=1, verbose_name='Bonuspunten (alle bekers omgegooid)')),
                ('round_duration_minutes', models.PositiveIntegerField(default=15, verbose_name='Rondetijd (minuten)')),
                ('round_started_at', models.DateTimeField(blank=True, null=True)),
                ('round_is_active', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#206bc4', max_length=7, verbose_name='Primaire kleur')),
                ('secondary_color', models.CharField(default='#4dabf7', max_length=7, verbose_name='Secundaire kleur')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Toernooi',
                'verbose_name_plural': 'Toernooien',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.tournament'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naam')),
                ('number', models.PositiveIntegerField(verbose_name='Nummer')),
                ('orientation', models.CharField(choices=[('horizontal', 'Horizontaal'), ('vertical', 'Verticaal')], default='horizontal', max_length=20)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Tafel',
                'verbose_name_plural': 'Tafels',
                'ordering': ['number'],
                'unique_together': {('tournament', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('round_robin', 'Poule'), ('quarterfinal', 'Kwartfinale'), ('semifinal', 'Halve finale'), ('third_place', '3e/4e plaats'), ('final', 'Finale')], default='round_robin', max_length=20)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('score1', models.PositiveIntegerField(default=0)),
                ('score2', models.PositiveIntegerField(default=0)),
                ('bonus_team1', models.BooleanField(default=False)),
                ('bonus_team2', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Gepland'), ('in_progress', 'Bezig'), ('finished', 'Afgelopen')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('bracket_slot', models.PositiveIntegerField(blank=True, null=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournament.table')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='tournament.team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='tournament.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Wedstrijd',
                'verbose_name_plural': 'Wedstrijden',
                'ordering': ['round_number', 'bracket_slot', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='round_robin', max_length=20)),
                ('played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('cups_scored', models.PositiveIntegerField(default=0)),
                ('cups_conceded', models.PositiveIntegerField(default=0)),
                ('bonus_points', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournament.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Stand',
                'verbose_name_plural': 'Standen',
                'ordering': ['-points', '-cups_scored'],
                'unique_together': {('tournament', 'team', 'phase')},
            },
        ),
    ]
