# Generated by Django 5.0.14 on 2026-05-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='table_display_cols',
            field=models.PositiveIntegerField(default=4, verbose_name='Kolommen (tafels weergave)'),
        ),
    ]
