# Generated by Django 5.0.14 on 2026-05-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_table_display_cols'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='table_orientation',
            field=models.CharField(choices=[('horizontal', 'Horizontaal (ploegen links/rechts)'), ('vertical', 'Verticaal (ploegen boven/onder)')], default='horizontal', max_length=20, verbose_name='Tafels orientatie'),
        ),
    ]
