# Generated by Django 5.0.14 on 2026-05-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_table_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='round_elapsed_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
