# Generated by Django 5.0.14 on 2026-05-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_round_elapsed_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Verborgen in publiek scorebord'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_timer_in_live',
            field=models.BooleanField(default=True, verbose_name='Timer tonen in live scherm'),
        ),
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('round_robin', 'Competitiefase'), ('quarterfinal', 'Kwartfinale'), ('semifinal', 'Halve finale'), ('third_place', '3e/4e plaats'), ('final', 'Finale')], default='round_robin', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Competitiefase (iedereen speelt X keer)'), ('knockout', 'Knock-out (kwart/semi/finale)'), ('combined', 'Combinatie (competitiefase → knock-out)')], default='round_robin', max_length=20, verbose_name='Formaat'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='games_per_team',
            field=models.PositiveIntegerField(default=3, verbose_name='Wedstrijden per ploeg'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('setup', 'Opzet'), ('round_robin', 'Competitiefase'), ('knockout', 'Knock-out'), ('finished', 'Afgelopen')], default='setup', max_length=20),
        ),
    ]
