# Generated by Django 5.0.14 on 2026-05-31 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_match_hidden_tournament_show_timer_in_live_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='drink_type',
        ),
        migrations.AddField(
            model_name='tournament',
            name='final_ranking_enabled',
            field=models.BooleanField(default=False, verbose_name='Finale ranking inschakelen'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='playoff_count',
            field=models.PositiveIntegerField(default=4, verbose_name='Ploegen in play-offs'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='playoff_enabled',
            field=models.BooleanField(default=False, verbose_name='Play-offs inschakelen'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sound_enabled',
            field=models.BooleanField(default=False, verbose_name='Geluiden inschakelen'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sound_end',
            field=models.FileField(blank=True, null=True, upload_to='sounds/', verbose_name='Geluid ronde einde'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sound_start',
            field=models.FileField(blank=True, null=True, upload_to='sounds/', verbose_name='Geluid ronde start'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sound_warning',
            field=models.FileField(blank=True, null=True, upload_to='sounds/', verbose_name='Geluid 30s waarschuwing'),
        ),
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('round_robin', 'Competitiefase'), ('quarterfinal', 'Kwartfinale'), ('semifinal', 'Halve finale'), ('third_place', '3e/4e plaats'), ('final', 'Finale'), ('playoff', 'Play-off'), ('final_ranking', 'Finale ranking')], default='round_robin', max_length=20),
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Naam')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drinks/', verbose_name='Foto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drinks', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
            ],
            options={
                'verbose_name': 'Drank',
                'verbose_name_plural': 'Dranken',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.drink', verbose_name='Drank'),
        ),
    ]
