# Generated by Django 5.0.14 on 2026-05-31 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_remove_team_drink_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_tournaments', to='tournament.drink', verbose_name='Standaarddrank'),
        ),
    ]
