# Generated by Django 5.0.14 on 2026-05-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tournament_default_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='active_table_filter',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Actieve fase voor tafelpagina'),
        ),
    ]
