# Generated by Django 5.0.14 on 2026-05-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_tournament_active_table_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='schedule_efficient',
            field=models.BooleanField(default=False, help_text='Vult lege tafels op met wedstrijden van de volgende ronde zodat alle tafels maximaal bezet zijn.', verbose_name='Efficiënt speelschema'),
        ),
    ]
