# Generated by Django 5.0.14 on 2026-06-01 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_tournament_show_drinks_on_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='display_group_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('round_robin', 'Competitiefase'), ('group', 'Pouleronde'), ('quarterfinal', 'Kwartfinale'), ('semifinal', 'Halve finale'), ('third_place', '3e/4e plaats'), ('final', 'Finale'), ('playoff', 'Play-off'), ('final_ranking', 'Finale ranking')], default='round_robin', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Competitiefase (iedereen speelt X keer)'), ('knockout', 'Knock-out (kwart/semi/finale)'), ('combined', 'Combinatie (competitiefase → knock-out)'), ('groups', 'Poules (poulecompetitie → knock-out)')], default='round_robin', max_length=20, verbose_name='Formaat'),
        ),
        migrations.CreateModel(
            name='DisplayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Groep', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_groups', to='tournament.tournament')),
            ],
            options={
                'verbose_name': 'Weergavegroep',
                'verbose_name_plural': 'Weergavegroepen',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='display_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournament.displaygroup', verbose_name='Weergavegroep'),
        ),
    ]
