# Generated by Django 5.0.14 on 2026-06-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_display_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='custom_rules',
            field=models.TextField(blank=True, default='', verbose_name='Aanvullende afspraken (aanpasbaar)'),
        ),
    ]
