# Generated by Django 5.0.14 on 2026-06-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_add_custom_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='public_password',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="Wachtwoord publieke pagina's"),
        ),
        migrations.AddField(
            model_name='tournament',
            name='public_refresh_seconds',
            field=models.PositiveIntegerField(default=5, verbose_name="Verversingstijd publieke pagina's (seconden)"),
        ),
    ]
