# Generated by Django 5.0.14 on 2026-06-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_add_public_refresh_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='groups_ko_per_group',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='groups_playoff_per_group',
        ),
    ]
