# Generated by Django 5.0.14 on 2026-06-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_remove_groups_per_group_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='show_public_rules',
            field=models.BooleanField(default=True, verbose_name='Afspraken tonen'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_public_scoreboard',
            field=models.BooleanField(default=True, verbose_name='Scorebord tonen'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_public_standings',
            field=models.BooleanField(default=True, verbose_name='Stand tonen'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_public_tables',
            field=models.BooleanField(default=True, verbose_name='Tafels tonen'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='show_public_timer',
            field=models.BooleanField(default=True, verbose_name='Timer tonen'),
        ),
    ]
