# Generated by Django 5.0.14 on 2026-06-16 11:37

import tournament.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_tournament_show_public_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tiebreaker_order',
            field=models.JSONField(default=tournament.models.Tournament._tiebreaker_default, verbose_name='Volgorde gelijkstand'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='show_public_scoreboard',
            field=models.BooleanField(default=True, verbose_name='Wedstrijden tonen'),
        ),
    ]
