# Generated by Django 6.0.6 on 2026-08-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_tournament_show_public_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='golden_goal_team1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='golden_goal_team2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='golden_goal_enabled',
            field=models.BooleanField(default=False, help_text='Bij gelijkstand in een knock-outwedstrijd gaat de ploeg door die als eerste scoorde.', verbose_name='Golden goal inschakelen'),
        ),
    ]
